version: '3'
services:
  php:
    container_name: php-apache-sec20
    # image: php:7.3-apache
    build: .
    volumes:
      - ./php://var/www/html/
    ports:
      - 8007:80
    depends_on:
      - db
  db:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATADASE: db_test
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3307"